services:
  # Transmission - BitTorrent Client
  transmission:
    image: "transmission:4.1.1"
    container_name: "transmission"
    build:
      context: .
      dockerfile: "transmission.Dockerfile"
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    user: "${PUID}:${PGID}"
    security_opt:
      - "label=disable"
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - "/mnt/downloads:/home/transmission/downloads"
      - "${APPDATA}/transmission/config:/home/transmission/config"
      - "${APPDATA}/transmission/incomplete:/home/transmission/incomplete"
      - "${APPDATA}/transmission/scripts:/home/transmission/scripts"
      - "${APPDATA}/transmission/watch:/home/transmission/watch"
    environment:
      TZ: "${TZ}"
      TELEGRAM_ADMIN_ID_FILE: /run/secrets/telegram_admin_id
      TELEGRAM_API_TOKEN_FILE: /run/secrets/telegram_api_token
    secrets:
      - telegram_admin_id
      - telegram_api_token
    networks:
      - "pi-net"
    restart: unless-stopped